options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get update && apt-get install -y python3 python3-pip
        python3 your_script.py
