options:
  logging: CLOUD_LOGGING_ONLY

steps:
#  - name: 'ubuntu'
#    entrypoint: 'bash'
#    args:
#      - '-c'
#      - |
#        apt-get update && apt-get install -y python3 python3-pip
#        python3 main.py

  - name: 'python:3.10'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
        pytest
      
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'  # Cloud SDK image
    entrypoint: 'gcloud'
    args:
      [
        'run', 'deploy', 'test-python',
        '--source', '.',
        '--region', 'us-central1',
        '--allow-unauthenticated',
      ]
